locals {
  docdb_client_b64   = base64encode(file("${path.module}/../../../challenge1/docdb_client.py"))
  retail_dataset_b64 = base64encode(file("${path.module}/../../../challenge1/retail_dataset.json"))

  user_data = join("", [
    "#!/bin/bash\n",
    "set -e\n",
    "exec > /var/log/user-data.log 2>&1\n",
    "\n",
    "yum update -y\n",
    "yum install -y python3 python3-pip\n",
    "\n",
    "mkdir -p /opt/skills-nosql\n",
    "\n",
    "curl -sSL -o /opt/skills-nosql/global-bundle.pem https://truststore.pki.rds.amazonaws.com/global/global-bundle.pem\n",
    "\n",
    "pip3 install pymongo boto3\n",
    "\n",
    "printf '%s' '",
    local.docdb_client_b64,
    "' | base64 -d > /opt/skills-nosql/docdb_client.py\n",
    "\n",
    "printf '%s' '",
    local.retail_dataset_b64,
    "' | base64 -d > /opt/skills-nosql/retail_dataset.json\n",
    "\n",
    "chmod +x /opt/skills-nosql/docdb_client.py\n",
    "\n",
    "cat > /etc/systemd/system/nosql-app.service << 'SERVICE_EOF'\n",
    "[Unit]\n",
    "Description=Skills NoSQL Client Application\n",
    "After=network.target\n",
    "\n",
    "[Service]\n",
    "Type=simple\n",
    "WorkingDirectory=/opt/skills-nosql\n",
    "ExecStart=/usr/bin/python3 /opt/skills-nosql/docdb_client.py serve\n",
    "Restart=always\n",
    "RestartSec=5\n",
    "Environment=AWS_DEFAULT_REGION=ap-northeast-2\n",
    "\n",
    "[Install]\n",
    "WantedBy=multi-user.target\n",
    "SERVICE_EOF\n",
    "\n",
    "systemctl daemon-reload\n",
    "systemctl enable --now nosql-app\n",
    "\n",
    "for i in 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20; do\n",
    "  if curl -sf http://localhost:8080/health > /dev/null 2>&1; then\n",
    "    echo 'App is ready'\n",
    "    break\n",
    "  fi\n",
    "  sleep 10\n",
    "done\n",
    "\n",
    "python3 /opt/skills-nosql/docdb_client.py seed || true\n",
    "echo 'Data seeded'\n",
    "\n",
    "python3 << 'INDEXEOF'\n",
    "import json, boto3, time\n",
    "from datetime import datetime\n",
    "from pymongo import MongoClient, ASCENDING, DESCENDING\n",
    "\n",
    "region = 'ap-northeast-2'\n",
    "sm = boto3.client('secretsmanager', region_name=region)\n",
    "\n",
    "for _ in range(30):\n",
    "    try:\n",
    "        resp = sm.get_secret_value(SecretId='skills-nosql-docdb-secret')\n",
    "        secret = json.loads(resp['SecretString'])\n",
    "        break\n",
    "    except Exception as e:\n",
    "        print(f'Waiting for secret: {e}')\n",
    "        time.sleep(10)\n",
    "\n",
    "client = MongoClient(\n",
    "    host=secret['host'],\n",
    "    port=27017,\n",
    "    username=secret['username'],\n",
    "    password=secret['password'],\n",
    "    tls=True,\n",
    "    tlsCAFile='/opt/skills-nosql/global-bundle.pem',\n",
    "    retryWrites=False,\n",
    "    authSource='admin'\n",
    ")\n",
    "db = client['skills_retail']\n",
    "\n",
    "db.orders.create_index([('orderId', ASCENDING)], unique=True, name='idx_orderId_unique')\n",
    "db.orders.create_index([('customerId', ASCENDING), ('createdAt', DESCENDING)], name='idx_customerId_createdAt')\n",
    "db.orders.create_index([('status', ASCENDING), ('dueAt', ASCENDING)], name='idx_status_dueAt')\n",
    "\n",
    "db.products.create_index([('productId', ASCENDING)], unique=True, name='idx_productId_unique')\n",
    "db.products.create_index([('warehouseId', ASCENDING), ('stock', ASCENDING)], name='idx_warehouseId_stock')\n",
    "\n",
    "db.sessions.create_index([('sessionId', ASCENDING)], unique=True, name='idx_sessionId_unique')\n",
    "db.sessions.create_index([('expiresAt', ASCENDING)], expireAfterSeconds=0, name='idx_expiresAt_ttl')\n",
    "db.sessions.create_index([('customerId', ASCENDING), ('lastSeen', DESCENDING)], name='idx_customerId_lastSeen')\n",
    "\n",
    "client.close()\n",
    "print('Indexes created successfully!')\n",
    "INDEXEOF\n",
    "\n",
    "echo 'User data completed!'\n",
  ])
}

resource "aws_instance" "nosql_client" {
  ami                         = var.ami_id
  instance_type               = var.instance_type
  subnet_id                   = var.public_subnet_id
  vpc_security_group_ids      = [var.client_sg_id]
  iam_instance_profile        = var.instance_profile_name
  associate_public_ip_address = true
  user_data_base64            = base64gzip(local.user_data)
  user_data_replace_on_change = true

  tags = {
    Name = "skills-nosql-client-ec2"
  }
}
